#line 2 "2005053.cpp"

#line 4 "2005053.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[277] =
    {   0,
       30,   30,   72,   70,   71,   25,   71,16402,   70,   71,
       69,   70,   71,   12,   70,   71,   38,   70,   71,   28,
       70,   71,   26,   70,   71,   37,   70,   71,    3,   70,
       71,    4,   70,   71,   13,   70,   71,    9,   70,   71,
       13,   70,   71,   31,   70,   71,   28,   70,   71,   29,
       30,   70,   71,   10,   70,   71,   27,   70,   71,   11,
       70,   71,   27,   70,   71,    2,   70,   71,    2,   70,
       71,    7,   70,   71,    8,   70,   71,   26,   70,   71,
        2,   70,   71,    2,   70,   71,    2,   70,   71,    2,
       70,   71,    2,   70,   71,    2,   70,   71,    2,   70,

       71,    2,   70,   71,    2,   70,   71,    2,   70,   71,
        5,   70,   71,   26,   70,   71,    6,   70,   71,   19,
       70,   71,   16,   69,   70,   71,   55,   71,   39,   71,
       71,   56,   71,   43,   71,   60,   71,   58,   71,   60,
       71,   60,   71,   68,   71,   67,   71,   66,   68,   71,
       68,   71,   24,   71,   20,   24,   71,   22,   71,   24,
       71,   21,   24,   71,   23,   24,   71, 8210,   17, 8210,
       25,16402,   69,   27,   15,   37,   36,   14,   31,   30,
       31,   57,   61,   31,   29,   30,   33,   33,   26,    2,
       32,    2,   30,    2,    2,    2,    2,    2,    1,    2,

        2,    2,    2,    1,    2,    2,    2,    2,    2,    2,
       16,   69,   39,   42,   41,   53,   52,   51,   54,   48,
       47,   49,   45,   50,   44,   46,   58,   59,   65,   64,
       63,   22,   21,   37,   34,   31,   31,   33,   30,   33,
       30,   32,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,   40,   62,   35,   31,   30,   31,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2
    } ;

static const flex_int16_t yy_accept[183] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    6,    9,   11,   14,   17,   20,   23,   26,
       29,   32,   35,   38,   41,   44,   47,   50,   54,   57,
       60,   63,   66,   69,   72,   75,   78,   81,   84,   87,
       90,   93,   96,   99,  102,  105,  108,  111,  114,  117,
      120,  123,  127,  129,  131,  132,  134,  136,  138,  140,
      142,  144,  146,  148,  151,  153,  155,  158,  160,  162,
      165,  168,  169,  169,  171,  173,  174,  175,  176,  177,
      178,  178,  179,  180,  182,  182,  183,  184,  185,  187,
      188,  189,  190,  191,  191,  192,  194,  195,  196,  197,

      198,  199,  201,  202,  203,  204,  206,  207,  208,  209,
      210,  211,  213,  214,  215,  216,  217,  218,  219,  220,
      221,  222,  223,  224,  225,  226,  227,  228,  229,  230,
      231,  232,  233,  234,  235,  236,  236,  237,  237,  237,
      237,  238,  239,  241,  242,  243,  244,  245,  246,  247,
      248,  249,  250,  251,  252,  253,  254,  255,  256,  257,
      258,  258,  259,  259,  261,  262,  263,  264,  265,  266,
      267,  268,  269,  270,  271,  272,  273,  274,  275,  276,
      277,  277
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        2,    2,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,   31,   26,    1,   32,   33,   34,   35,

       36,   37,   26,   38,   39,   26,   40,   41,   26,   42,
       43,   26,   26,   44,   45,   46,   47,   48,   49,   26,
       26,   26,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    2,    2,    2,    2,    1,    1,    3,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    5,    1,    6,
        7,    1,    1,    1,    1,    7,    7,    1,    8,    1,
        1,    6,    6,    7,    7,    7,    6,    7,    7,    7,
        7,    6,    7,    6,    7,    6,    7,    6,    7,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[195] =
    {   0,
        0,   50,   50,   55,   57,   60,   62,   64,   72,   77,
      345,  346,   43,  340,  337,  318,  346,  346,  331,   59,
      346,  346,  325,  346,  322,   69,   78,   80,  346,   62,
      314,   78,    0,   91,  346,  346,  346,  293,   67,   77,
      295,   73,   80,  299,  285,  290,  294,  346,  280,  346,
      346,  324,  346,  346,  325,  346,  126,  346,  346,  324,
      308,  346,  346,  322,  114,  346,  346,  346,  321,  318,
      346,  346,    0,  346,   75,  317,  346,  346,  104,  346,
        0,  346,  105,  118,  132,  346,  346,  144,  155,    0,
      163,  346,    0,  122,  136,  152,  286,  276,  288,  277,

      281,  270,  271,  272,  270,    0,  267,  266,  272,  270,
      268,  295,  346,  346,  295,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      287,  346,  284,  137,  346,    0,  167,  175,  182,  186,
      190,    0,  162,  194,  198,  255,  249,  228,  225,  233,
      231,  227,  195,  176,  171,  178,  168,  346,  346,  346,
      140,  200,  204,  208,  165,  162,  151,  152,  145,  145,
      152,  115,  102,  100,   99,   86,   83,   47,   27,   21,
      346,  229,  237,  245,  253,  261,  269,  273,  275,  280,
      288,  294,  297,  302

    } ;

static const flex_int16_t yy_def[195] =
    {   0,
      181,    1,  182,  182,  183,  183,  184,  184,  185,  185,
      181,  181,  186,  181,  181,  181,  181,  181,  181,  187,
      181,  181,  181,  181,  181,  181,  181,  188,  181,  181,
      181,  181,  189,  189,  181,  181,  181,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  190,  181,  186,  181,  181,  181,  191,  181,
      192,  181,  181,  181,  181,  181,  181,  181,  188,  193,
      193,  181,  189,  181,  181,   34,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  191,  181,  194,  181,  181,  181,  181,
      181,  193,   91,  181,  181,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  181,  181,  181,
      181,  181,  181,  181,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
        0,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181

    } ;

static const flex_int16_t yy_nxt[399] =
    {   0,
       12,   12,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   18,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   32,   33,   34,   35,   12,   36,
       37,   33,   38,   39,   40,   41,   42,   33,   43,   33,
       33,   33,   33,   44,   45,   33,   33,   46,   47,   48,
       49,   50,   51,   54,   55,   52,  106,   56,   54,   55,
       59,   60,   56,   59,   60,   63,   64,   63,   64,   80,
       61,   73,  106,   61,   67,   68,   69,   70,   57,   67,
       68,   69,   70,   57,   92,   77,   83,   81,   84,   84,
       65,   86,   65,  180,   74,   85,   87,   88,   98,   89,

       89,   77,   92,   73,   99,   94,   91,   94,   95,  100,
       96,   96,  101,  104,  135,  105,  106,  130,  131,  102,
      106,  107,   83,   71,  137,  137,   74,  106,   71,  114,
      115,  138,  136,  116,  106,   83,  117,   84,   84,   95,
      179,  144,  144,  178,  139,  118,  140,  160,  140,   95,
      106,  141,  141,   95,  119,  145,  145,  120,  121,  162,
      162,   83,  122,   84,   84,  136,  181,  123,  181,  124,
       85,  125,   88,  126,   89,   89,  181,   94,  181,   94,
       95,   91,  143,  143,   83,  177,  137,  137,  176,  161,
      106,  161,  175,  138,  162,  162,  163,  174,  163,   95,

      173,  164,  164,   95,  106,  141,  141,   95,  172,  141,
      141,   95,  106,  144,  144,   95,  171,  145,  145,  162,
      162,   95,  170,  164,  164,   95,  169,  164,  164,   53,
       53,   53,   53,   53,   53,   53,   53,   58,   58,   58,
       58,   58,   58,   58,   58,   62,   62,   62,   62,   62,
       62,   62,   62,   66,   66,   66,   66,   66,   66,   66,
       66,   72,  106,  168,  167,   72,   72,   72,   72,   79,
      166,  106,   79,   79,   79,   79,   79,   90,   90,   90,
       93,   93,   72,   72,  106,   72,  165,   72,  134,  133,
      159,  134,  134,  134,  134,  134,   79,   79,  158,   79,

      112,   79,  142,  142,  134,  134,  157,  134,  156,  134,
      155,  154,  106,  106,  153,  152,  151,  150,  149,  148,
      147,  146,   76,  133,  132,  129,  128,  127,  113,  112,
       78,  111,  110,  109,  108,  103,   97,   77,   82,   82,
       78,   77,   76,   75,  181,   11,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181

    } ;

static const flex_int16_t yy_chk[399] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    3,    3,    2,  180,    3,    4,    4,
        5,    5,    4,    6,    6,    7,    7,    8,    8,   20,
        5,   13,  179,    6,    9,    9,    9,    9,    3,   10,
       10,   10,   10,    4,   30,   30,   26,   20,   26,   26,
        7,   27,    8,  178,   13,   26,   27,   28,   39,   28,

       28,   32,   32,   75,   39,   34,   28,   34,   34,   39,
       34,   34,   40,   42,   79,   42,   43,   65,   65,   40,
      177,   43,   83,    9,   83,   83,   75,  176,   10,   57,
       57,   83,   79,   57,  175,   84,   57,   84,   84,   94,
      174,   94,   94,  173,   84,   57,   85,  134,   85,   85,
      172,   85,   85,   95,   57,   95,   95,   57,   57,  161,
      161,   88,   57,   88,   88,  134,   96,   57,   96,   57,
       88,   57,   89,   57,   89,   89,  143,   91,  143,   91,
       91,   89,   91,   91,  137,  171,  137,  137,  170,  138,
      169,  138,  168,  137,  138,  138,  139,  167,  139,  139,

      166,  139,  139,  140,  165,  140,  140,  141,  157,  141,
      141,  144,  156,  144,  144,  145,  155,  145,  145,  162,
      162,  163,  154,  163,  163,  164,  153,  164,  164,  182,
      182,  182,  182,  182,  182,  182,  182,  183,  183,  183,
      183,  183,  183,  183,  183,  184,  184,  184,  184,  184,
      184,  184,  184,  185,  185,  185,  185,  185,  185,  185,
      185,  186,  152,  151,  150,  186,  186,  186,  186,  187,
      149,  148,  187,  187,  187,  187,  187,  188,  188,  188,
      189,  189,  190,  190,  147,  190,  146,  190,  191,  133,
      131,  191,  191,  191,  191,  191,  192,  192,  115,  192,

      112,  192,  193,  193,  194,  194,  111,  194,  110,  194,
      109,  108,  107,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   76,   70,   69,   64,   61,   60,   55,   52,
       49,   47,   46,   45,   44,   41,   38,   31,   25,   23,
       19,   16,   15,   14,   11,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181

    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2005053.l"




#line 8 "2005053.l"
#include<iostream>
#include<cstring>
#include<stdlib.h>
#include<string>
#include "2005053-SymbolTable.cpp"
FILE *logout;
FILE *tokenout;
int line_count=1;
int line_store=0;
int errors=0;
int indent=0;
int gotIndent=0;
int warning=0;
SymbolTable *obj=new SymbolTable(10);
string str;
string logStr;
string commentStr;
bool flag;
bool tabFlag;
using namespace std;
//chmod +x command.sh
char *ToUpper(char *text)
{    
    char *arr=new char[strlen(text)+1];
	//strcpy(arr,text);	
	for(int i=0;i<strlen(text);i++)
	{
		arr[i]=toupper(text[i]);
	}
	arr[strlen(text)]='\0';
	return arr;
}
void logPrint(string tokenName,char *lexeme,int lineno)
{
	 fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",lineno,tokenName.c_str(),lexeme); 
}

void tokenPrint(string tokenName,char *lexeme)
{
	fprintf(tokenout,"<%s, %s>\n",tokenName.c_str(),lexeme);
}
char *charPrint(char *lexeme)
{   
	char *ptr=new char[2];
	switch(lexeme[1])
	{   
		case 't':
		{
		    ptr[0]='\t';
			//return ptr;
			break;
		}
		case 'n':
		{
			ptr[0]='\n';
			break;
		}
		case '0':
	    {
		
		 ptr[0]='\0';
		 //return ptr;
		 break;
	    }
		case 'a':
		{
		
			ptr[0]='\a';
			break;
		
		}
		case 'r':
		{
			ptr[0]='\r';
			break;
		}
		case 'b':
		{
		
			ptr[0]='\b';
			break;
		}
		case 'v':
		{
			 ptr[0]='\v';
			 break;
		}
		case '"':
		{
			ptr[0]='\"';
			break;
		}
		case '\'':
		{
			ptr[0]='\'';
			break;
		}
		case 'f':
		{
			ptr[0]='f';
			break;
		}
		case '\\':
		{
			ptr[0]='\\';
			break;
		}

	}
	return ptr;
}
void  eofPrint()
{
	obj->PrintAllScope(logout);
	fprintf(logout,"Total lines: %d\n",line_count);
	fprintf(logout,"Total errors: %d\n",errors);
	fprintf(logout,"Total warnings: %d\n",warning);
}
#line 766 "2005053.cpp"
#line 767 "2005053.cpp"

#define INITIAL 0
#define StringState 1
#define multicomment 2
#define singlecomment 3
#define tabState 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 140 "2005053.l"

#line 999 "2005053.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 182 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 346 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 141 "2005053.l"
{fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
           fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext); 
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 144 "2005053.l"
{
	 //fprintf(tokenout,"<ID,%s>\n",yytext);
	 tokenPrint("ID",yytext);
	 bool flag=obj->Insert(yytext,"ID");
	 logPrint("ID",yytext,line_count);
	 //fprintf(logout,"Line# %d: Token <ID> Lexeme %s found\n",line_count,yytext); 
	 if(flag)
	 {
		 obj->PrintAllScope(logout);
		 
	 }
	 else{
		fprintf(logout,"\t%s already exists in the current ScopeTable\n",yytext);
	 }
	
   }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 160 "2005053.l"
{ tokenPrint("LPAREN",yytext);
      logPrint("LPAREN",yytext,line_count);
     //fprintf(logout,"Line# %d: Token <LPAREN> Lexeme %s found\n",line_count,yytext); 
	 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 164 "2005053.l"
{ tokenPrint("RPAREN",yytext);
     logPrint("RPAREN",yytext,line_count);
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 167 "2005053.l"
{ tokenPrint("LCURL",yytext);
     obj->EnterScope();
	 indent++;
	 logPrint("LCURL",yytext,line_count);
	 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 172 "2005053.l"
{ tokenPrint("RCURL",yytext);
     obj->ExitScope();
	 indent--;
	 logPrint("RCURL",yytext,line_count);
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 177 "2005053.l"
{ tokenPrint("LSQUARE",yytext);
    logPrint("LSQUARE",yytext,line_count);
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 180 "2005053.l"
{ 
	tokenPrint("RSQUARE",yytext);
     logPrint("RSQUARE",yytext,line_count); 
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 184 "2005053.l"
{ 
	tokenPrint("COMMA",yytext);
    logPrint("COMMA",yytext,line_count);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 188 "2005053.l"
{ 
	tokenPrint("SEMICOLON",yytext);
    logPrint("SEMICOLON",yytext,line_count); 
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 192 "2005053.l"
{ tokenPrint("ASSIGNOP",yytext);
       logPrint("ASSIGNOP",yytext,line_count);
 }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 195 "2005053.l"
{ tokenPrint("NOT",yytext);
       logPrint("NOT",yytext,line_count);
	 }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 198 "2005053.l"
{ tokenPrint("ADDOP",yytext);
         logPrint("ADDOP",yytext,line_count);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 200 "2005053.l"
{ tokenPrint("INCOP",yytext);
           logPrint("INCOP",yytext,line_count);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 202 "2005053.l"
{ tokenPrint("LOGICOP",yytext);logPrint("LOGICOP",yytext,line_count);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 203 "2005053.l"
{
	warning++;
	fprintf(logout,"Line# %d: Warning, tab requrired but got space.\n",line_count);
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 207 "2005053.l"
{
	line_count++;
	if(gotIndent!=(indent-1))
	{
		warning++;
	    fprintf(logout,"Line# %d: warning, %d of tabs needed but got %d tabs.\n",line_count,indent,gotIndent);	
	}	

}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 216 "2005053.l"
{
	line_count++;
	if(gotIndent!=indent)
	{
		warning++;
	    fprintf(logout,"Line# %d: warning, %d of tabs needed but got %d tabs.\n",line_count,indent,gotIndent);	
	}	
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 224 "2005053.l"
{
	BEGIN(tabState);
	gotIndent=1;
	tabFlag=false;	
}
	YY_BREAK

case 20:
YY_RULE_SETUP
#line 230 "2005053.l"
{
		gotIndent++;
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 233 "2005053.l"
{
		tabFlag=true;
	}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 237 "2005053.l"
{
		int c = int(yytext[0]); 
		unput(c);
		gotIndent=0;
		BEGIN(INITIAL);
	}
	YY_BREAK
case YY_STATE_EOF(tabState):
#line 243 "2005053.l"
{
		eofPrint();
		yyterminate();
		BEGIN(INITIAL);
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 248 "2005053.l"
{
	int c = int(yytext[0]); 
		if(tabFlag){
			warning++;
			fprintf(logout,"Line# %d: Warning, tab requrired but got space.\n",line_count);
		}
		else{	
			if(gotIndent!=(indent-1)){
				warning++;
				fprintf(logout,"Line# %d: warning, %d of tabs needed but got %d tabs.\n",line_count,indent,gotIndent);
			}		
		}
		unput(c);
		gotIndent=0;
		BEGIN(INITIAL);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 264 "2005053.l"
{
		int c = int(yytext[0]); 
		if(tabFlag){
			warning++;
			fprintf(logout,"Line# %d: Warning, tab requrired but got space.\n",line_count);
		}
		else{
			
			if(gotIndent!=indent){
				warning++;
				fprintf(logout,"Line# %d: warning, %d of tabs needed but got %d tabs.\n",line_count,indent,gotIndent);
			}		
		}
		unput(c);
		gotIndent=0;
		BEGIN(INITIAL);
	}
	YY_BREAK

case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 282 "2005053.l"
{line_count++;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 283 "2005053.l"
{ tokenPrint("BITOP",yytext);;
         logPrint("BITOP",yytext,line_count);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 285 "2005053.l"
{ tokenPrint("RELOP",yytext);
         logPrint("RELOP",yytext,line_count);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 287 "2005053.l"
{ tokenPrint("MULOP",yytext);
         logPrint("MULOP",yytext,line_count);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 289 "2005053.l"
{ tokenPrint("CONST_INT",yytext);
          logPrint("CONST_INT",yytext,line_count);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 291 "2005053.l"
{
	 tokenPrint("CONST_FLOAT",yytext);
     logPrint("CONST_FLOAT",yytext,line_count);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 295 "2005053.l"
{
	fprintf(logout,"Error at line# %d: TOO_MANY_DECIMAL_POINTS %s\n",line_count,yytext);
	errors++;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 299 "2005053.l"
{
	fprintf(logout,"Error at line# %d: ILLFORMED_NUMBER %s\n",line_count,yytext);
	errors++;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 303 "2005053.l"
{
	fprintf(logout,"Error at line# %d: INVALID_ID_SUFFIX_NUM_PREFIX %s\n",line_count,yytext);
	errors++;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 307 "2005053.l"
{
	char *temp=new char[strlen(yytext)-1];
	for(int i=1;i<strlen(yytext)-1;i++)
	{
			temp[i-1]=yytext[i];															
	}
	if(strlen(temp)>1)
	{   
		//cout<<strlen(temp)<<endl;
		tokenPrint("CONST_CHAR",charPrint(temp));
		logPrint("CONST_CHAR",charPrint(temp),line_count);
	}
	else{
		tokenPrint("CONST_CHAR",temp);
		logPrint("CONST_CHAR",temp,line_count);
	}
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 324 "2005053.l"
{
	fprintf(logout,"Error at line# %d: MULTICHAR_CONST_CHAR %s\n",line_count,yytext);
	errors++;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 329 "2005053.l"
{
	fprintf(logout,"Error at line# %d: EMPTY_CONST_CHAR %s\n",line_count,yytext);
	errors++;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 333 "2005053.l"
{
	fprintf(logout,"Error at line# %d: UNFINISHED_CONST_CHAR %s\n",line_count,yytext);
	errors++;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 337 "2005053.l"
{
    line_store=line_count;
	BEGIN(StringState);
	str = "";
	logStr="\"";
	flag=false;
}
	YY_BREAK

case YY_STATE_EOF(StringState):
#line 346 "2005053.l"
{
	string tokenName="UNFINISHED_STRING";
	fprintf(logout,"Error at line# %d: %s %s\n",line_count,tokenName.c_str(),logStr.c_str());
	errors++;
	eofPrint();
	yyterminate();
	BEGIN(INITIAL);
}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 354 "2005053.l"
{
	string tokenName="UNFINISHED_STRING";
	fprintf(logout,"Error at line# %d: %s %s\n",line_count,tokenName.c_str(),logStr.c_str());
	errors++;
	line_count++;
	BEGIN(INITIAL);
}
	YY_BREAK
case 40:
/* rule 40 can match eol */
#line 362 "2005053.l"
case 41:
/* rule 41 can match eol */
#line 363 "2005053.l"
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 363 "2005053.l"
{
   flag=true;
   line_count++;
   logStr +='\\';
   logStr +='\n';
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 370 "2005053.l"
{
	str +='\\';
	logStr += yytext;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 375 "2005053.l"
{
   str +='\t';
   logStr +=yytext;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 379 "2005053.l"
{
	str +='\n';
	logStr +=yytext;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 383 "2005053.l"
{
	str +='\v';
	logStr +=yytext;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 387 "2005053.l"
{
	str +='\b';
	logStr +=yytext;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 391 "2005053.l"
{
	str +='\a';
	logStr +=yytext;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 395 "2005053.l"
{
	str +='\f';
	logStr +=yytext;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 399 "2005053.l"
{
	str +='\r';
	logStr +=yytext;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 403 "2005053.l"
{
	str +='\0';
	logStr +=yytext;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 407 "2005053.l"
{
	str +='\'';
	logStr +=yytext;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 411 "2005053.l"
{
	str +='\"';
	logStr +=yytext;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 415 "2005053.l"
{
	str +='\\';
	logStr += yytext;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 421 "2005053.l"
{ str += yytext;logStr += yytext;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 422 "2005053.l"
{
	if(flag)
	{   
		logStr+="\"";
		fprintf(tokenout,"<MULTI LINE STRING, %s>\n",str.c_str());	
		string tokenName="MULTI LINE STRING";
		fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_store,tokenName.c_str(),logStr.c_str()); 
	}
	else{
		logStr+="\"";
		fprintf(tokenout,"<SINGLE LINE STRING, %s>\n",str.c_str());
		string tokenName="SINGLE LINE STRING";
		fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_store,tokenName.c_str(),logStr.c_str()); 
	
	}	
	BEGIN(INITIAL);
}
	YY_BREAK

case 57:
YY_RULE_SETUP
#line 442 "2005053.l"
{
	 BEGIN(multicomment);
	 line_store=line_count;
	 commentStr = "/*";	
}
	YY_BREAK

case YY_STATE_EOF(multicomment):
#line 448 "2005053.l"
{
	string tokenName="UNFINISHED_COMMENT";
	fprintf(logout,"Error at line# %d: %s %s\n",line_count,tokenName.c_str(),commentStr.c_str());
	errors++;
	eofPrint();
	yyterminate();
	BEGIN(INITIAL);
 }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 457 "2005053.l"
{
	commentStr +='\n';
	line_count++;	
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 461 "2005053.l"
{
  commentStr += "*/";	
  string tokenName="MULTI LINE COMMENT";
  fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_store,tokenName.c_str(),commentStr.c_str()); 
  BEGIN(INITIAL);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 467 "2005053.l"
{commentStr +=yytext;}
	YY_BREAK

case 61:
YY_RULE_SETUP
#line 470 "2005053.l"
{
	 line_store=line_count;
	 BEGIN(singlecomment);
	 commentStr = "//";	
}
	YY_BREAK

case YY_STATE_EOF(singlecomment):
#line 476 "2005053.l"
{
	eofPrint();
	yyterminate();
	BEGIN(INITIAL);
 }
	YY_BREAK
case 62:
/* rule 62 can match eol */
#line 482 "2005053.l"
case 63:
/* rule 63 can match eol */
#line 483 "2005053.l"
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 483 "2005053.l"
{
   line_count++;
   commentStr +='\\';
   commentStr +='\n';
}
	YY_BREAK
case 65:
/* rule 65 can match eol */
#line 490 "2005053.l"
case 66:
/* rule 66 can match eol */
#line 491 "2005053.l"
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 491 "2005053.l"
{
	string tokenName="SINGLE LINE COMMENT";
    fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_store,tokenName.c_str(),commentStr.c_str()); 
	line_count++;	
	BEGIN(INITIAL);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 497 "2005053.l"
{commentStr +=yytext;}
	YY_BREAK

case 69:
YY_RULE_SETUP
#line 499 "2005053.l"
{ }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 500 "2005053.l"
{
	string tokenName="UNRECOGNIZED_CHAR";
	errors++;
	fprintf(logout,"Error at line# %d: %s %s\n",line_count,tokenName.c_str(),yytext);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 505 "2005053.l"
{
	eofPrint();
	yyterminate();
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 510 "2005053.l"
ECHO;
	YY_BREAK
#line 1737 "2005053.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 182 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 2;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 182 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 181);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 510 "2005053.l"

int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
    logout= fopen("log.txt","w");
	tokenout= fopen("token.txt","w");
	yyin= fin;
	yylex();
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	return 0;
}
