
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[157] =
    {   0,
       32,   32,    0,    0,    0,    0,    0,    0,   74,   72,
       71,   27,   72,   22,   40,   30,   28,   39,   13,   14,
       23,   19,   23,   33,   30,   31,   20,   29,   21,   29,
       12,   12,   17,   18,   28,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   15,   28,   16,   57,   41,   73,
       58,   45,   62,   60,   62,   62,   70,   69,   68,   70,
       71,   27,   29,   26,   39,   38,    0,   24,   25,   33,
       32,    0,   59,   63,   33,   31,   35,   35,   28,   12,
        0,   34,   12,   12,    5,   12,   12,   12,    1,   12,
       12,   12,   12,   12,   41,   44,   43,   55,   54,   53,

       56,   50,   49,   51,   47,   52,   46,   48,   60,   61,
       67,   66,   65,   39,   36,    0,   33,    0,    0,    0,
       33,   35,   32,   32,   34,   12,   12,   12,    3,    6,
       12,   12,   12,   12,   42,   64,   37,    0,   33,    0,
       32,    7,    2,   12,   12,   12,   10,   12,    9,   12,
       12,    4,   12,   11,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        2,    2,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,   31,   26,    1,   32,   33,   34,   35,

       36,   37,   26,   38,   39,   26,   26,   40,   26,   41,
       42,   43,   26,   44,   45,   46,   47,   48,   49,   26,
       26,   26,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    2,    2,    2,    2,    1,    1,    3,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    5,    1,    6,
        7,    1,    1,    1,    1,    7,    7,    1,    4,    1,
        1,    6,    6,    7,    7,    7,    6,    7,    7,    7,
        6,    7,    7,    6,    7,    6,    7,    6,    7,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[167] =
    {   0,
        0,    0,   49,   51,   56,   58,   60,   62,  279,  280,
       65,  280,  274,  253,  280,  280,  266,   47,  280,  280,
      260,  280,  257,   61,   55,   65,  280,   70,  249,   71,
        0,   82,  280,  280,  280,  234,  229,  230,   33,   64,
      225,  232,  225,  228,  280,  214,  280,  280,  280,  260,
      280,  102,  280,  280,  258,  237,  280,  280,  245,  104,
       81,  280,  280,  280,   87,  280,    0,  280,  280,   94,
       99,  112,  280,  280,  120,  124,    0,  137,  280,    0,
      141,  145,  108,  216,    0,  192,  194,  167,    0,  161,
      160,  149,  152,  148,  280,  280,  179,  280,  280,  280,

      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  176,  107,  280,    0,  149,  157,  164,  168,
      172,    0,  156,  176,  180,  131,  132,  132,    0,    0,
      119,  109,  118,  109,  280,  280,  280,  182,  184,  188,
      192,    0,    0,   91,   82,   80,    0,   75,    0,   64,
       49,    0,   36,    0,    0,  280,  213,  220,  227,  234,
      237,  239,  246,  251,  252,  257
    } ;

static const flex_int16_t yy_def[167] =
    {   0,
      156,    1,  157,  157,  158,  158,  159,  159,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  160,  156,  156,
      156,  156,  156,  156,  156,  161,  156,  156,  156,  156,
      162,  162,  156,  156,  156,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  163,  156,  164,  156,  156,  156,
      156,  156,  156,  156,  156,  161,  165,  165,  156,  162,
      156,  156,   32,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  163,  156,  166,  156,  156,  156,  156,
      156,  165,   78,  156,  156,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  156,  156,  156,  156,  156,  156,
      156,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,    0,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156
    } ;

static const flex_int16_t yy_nxt[333] =
    {   0,
       10,   10,   11,   12,   13,   11,   14,   15,   16,   17,
       18,   19,   20,   16,   21,   22,   23,   24,   25,   26,
       26,   27,   28,   29,   30,   31,   32,   33,   10,   34,
       35,   31,   31,   36,   37,   38,   39,   31,   40,   31,
       31,   31,   41,   42,   31,   31,   31,   43,   44,   45,
       46,   47,   49,   50,   49,   50,   51,   66,   51,   54,
       55,   54,   55,   58,   59,   58,   59,   61,   73,   56,
       61,   56,   87,   74,   88,   67,  155,   52,   70,   52,
       71,   71,   75,   61,   76,   76,   61,   72,   60,  154,
       60,   78,   79,   63,   63,   79,   81,  115,   81,   82,

       89,   83,   83,  153,   90,   96,   97,  112,  113,   98,
      152,   70,   99,  117,  117,  116,   70,  137,   71,   71,
      118,  100,  156,  151,  156,  119,  120,  150,  120,   82,
      101,  121,  121,  102,  103,  116,  149,   70,  104,   71,
       71,   75,  105,   76,   76,  106,   72,  107,  148,  108,
       78,   81,  147,   81,   82,  146,  123,  123,   82,  145,
      124,  124,   82,  144,  125,  125,   70,  143,  117,  117,
      156,  138,  156,  138,  142,  118,  139,  139,  140,  136,
      140,   82,  135,  141,  141,   82,  134,  121,  121,   82,
      133,  121,  121,   82,  132,  124,  124,   82,  131,  125,

      125,  139,  139,  139,  139,   82,  130,  141,  141,   82,
      129,  141,  141,   48,   48,   48,   48,   48,   48,   48,
       53,   53,   53,   53,   53,   53,   53,   57,   57,   57,
       57,   57,   57,   57,   65,  128,  127,   65,   65,   65,
       65,   77,   77,   77,   80,   80,  114,  126,  111,  114,
      114,  114,  114,   65,   65,  110,   65,  122,  122,  114,
      114,  109,  114,   95,   64,   94,   93,   92,   91,   86,
       85,   84,   63,   69,   68,   64,   63,   62,  156,    9,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156
    } ;

static const flex_int16_t yy_chk[333] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    3,   18,    4,    5,
        5,    6,    6,    7,    7,    8,    8,   11,   25,    5,
       11,    6,   39,   25,   39,   18,  153,    3,   24,    4,
       24,   24,   26,   61,   26,   26,   61,   24,    7,  151,
        8,   26,   28,   28,   30,   30,   32,   65,   32,   32,

       40,   32,   32,  150,   40,   52,   52,   60,   60,   52,
      148,   70,   52,   70,   70,   65,   71,  114,   71,   71,
       70,   52,   83,  146,   83,   71,   72,  145,   72,   72,
       52,   72,   72,   52,   52,  114,  144,   75,   52,   75,
       75,   76,   52,   76,   76,   52,   75,   52,  134,   52,
       76,   78,  133,   78,   78,  132,   78,   78,   81,  131,
       81,   81,   82,  128,   82,   82,  117,  127,  117,  117,
      123,  118,  123,  118,  126,  117,  118,  118,  119,  113,
      119,  119,   97,  119,  119,  120,   94,  120,  120,  121,
       93,  121,  121,  124,   92,  124,  124,  125,   91,  125,

      125,  138,  138,  139,  139,  140,   90,  140,  140,  141,
       88,  141,  141,  157,  157,  157,  157,  157,  157,  157,
      158,  158,  158,  158,  158,  158,  158,  159,  159,  159,
      159,  159,  159,  159,  160,   87,   86,  160,  160,  160,
      160,  161,  161,  161,  162,  162,  163,   84,   59,  163,
      163,  163,  163,  164,  164,   56,  164,  165,  165,  166,
      166,   55,  166,   50,   46,   44,   43,   42,   41,   38,
       37,   36,   29,   23,   21,   17,   14,   13,    9,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2005053.l"



#line 8 "2005053.l"
#include<iostream>
#include<cstring>
#include<stdlib.h>
#include<string>
#include "2005053-SymbolTable.h"
#include "y.tab.h"

using namespace std;

extern FILE *logout;
extern FILE *tokenout;
int line_count=1;
int line_store=0;
bool flag=false;
extern ScopeTable *symtable;
SymbolInfo *ptr;
string str;
string logStr;
string commentStr;
extern YYSTYPE yylval;

//chmod +x command.sh
char *ToUpper(char *text)
{    
    char *arr=new char[strlen(text)+1];
	//strcpy(arr,text);	
	for(int i=0;i<strlen(text);i++)
	{
		arr[i]=toupper(text[i]);
	}
	arr[strlen(text)]='\0';
	return arr;
}
void tokenPrint(string tokenName,char *lexeme)
{
	fprintf(tokenout,"<%s, %s>\n",tokenName.c_str(),lexeme);
}
void logPrint(string tokenName,char *lexeme,int lineno)
{
	 fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",lineno,tokenName.c_str(),lexeme); 
}

char *charPrint(char *lexeme)
{   
	char *ptr=new char[2];
	switch(lexeme[1])
	{   
		case 't':
		{
		    ptr[0]='\t';
			//return ptr;
			break;
		}
		case 'n':
		{
			ptr[0]='\n';
			break;
		}
		case '0':
	    {
		
		 ptr[0]='\0';
		 //return ptr;
		 break;
	    }
		case 'a':
		{
		
			ptr[0]='\a';
			break;
		
		}
		case 'r':
		{
			ptr[0]='\r';
			break;
		}
		case 'b':
		{
		
			ptr[0]='\b';
			break;
		}
		case 'v':
		{
			 ptr[0]='\v';
			 break;
		}
		case '"':
		{
			ptr[0]='\"';
			break;
		}
		case '\'':
		{
			ptr[0]='\'';
			break;
		}
		case 'f':
		{
			ptr[0]='f';
			break;
		}
		case '\\':
		{
			ptr[0]='\\';
			break;
		}

	}
	return ptr;
}

#line 688 "lex.yy.c"
#line 689 "lex.yy.c"

#define INITIAL 0
#define StringState 1
#define multicomment 2
#define singlecomment 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 131 "2005053.l"

#line 911 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 157 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 280 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 132 "2005053.l"
{
	 fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
	 fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	 ptr=new SymbolInfo(yytext,"IF");
	 ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);
	 yylval.symbol=ptr;
	 return IF;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 141 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"ELSE");
	    ptr->startlineSetter(line_count);
	    ptr->endlineSetter(line_count);
	   yylval.symbol=ptr;
	   return ELSE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 150 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"FOR");
	   ptr->startlineSetter(line_count);
	   ptr->endlineSetter(line_count);
	   yylval.symbol=ptr;
	   return FOR;	
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 159 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"WHILE");
	   ptr->startlineSetter(line_count);
	   ptr->endlineSetter(line_count);
	   yylval.symbol=ptr;
	   return WHILE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 168 "2005053.l"
{ 
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"DO");
	   ptr->startlineSetter(line_count);
	   ptr->endlineSetter(line_count);
	   yylval.symbol=ptr;
	   return DO;	
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 177 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"INT");
	   ptr->startlineSetter(line_count);
	   ptr->endlineSetter(line_count);
	   yylval.symbol=ptr;
	   return INT;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 186 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"CHAR");
	    ptr->startlineSetter(line_count);
	    ptr->endlineSetter(line_count);   
	   yylval.symbol=ptr;
	   return CHAR;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 195 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"PRINTLN");
	    ptr->startlineSetter(line_count);
	    ptr->endlineSetter(line_count);   
	   yylval.symbol=ptr;
	   return PRINTLN;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 204 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"FLOAT");
	   ptr->startlineSetter(line_count);
	    ptr->endlineSetter(line_count);   
	   yylval.symbol=ptr;
	   return FLOAT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 214 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"VOID");
	   ptr->startlineSetter(line_count);
	    ptr->endlineSetter(line_count);   
	   yylval.symbol=ptr;
	   return VOID;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 223 "2005053.l"
{
	   fprintf(tokenout,"<%s, %s>\n",ToUpper(yytext),yytext);
       fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,ToUpper(yytext),yytext);
	   ptr=new SymbolInfo(yytext,"RETURN");
	   ptr->startlineSetter(line_count);
	    ptr->endlineSetter(line_count);   
	   yylval.symbol=ptr;
	   return RETURN;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 234 "2005053.l"
{
	
     fprintf(logout,"Line# %d: Token <ID> Lexeme %s found\n",line_count,yytext); 
	 tokenPrint("ID",yytext);
	 ptr=new SymbolInfo(yytext,"ID");
	 ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);   
	 yylval.symbol=ptr;
	 return ID;
	
   }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 245 "2005053.l"
{ //tokenPrint("LPAREN",yytext);
      
      logPrint("LPAREN",yytext,line_count);
	  tokenPrint("LPAREN",yytext);
	  ptr=new SymbolInfo(yytext,"LPAREN");
	  ptr->startlineSetter(line_count);
	  ptr->endlineSetter(line_count);  
	  yylval.symbol=ptr;
	  return LPAREN;
     //fprintf(logout,"Line# %d: Token <LPAREN> Lexeme %s found\n",line_count,yytext); 
	 }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 256 "2005053.l"
{ //tokenPrint("RPAREN",yytext);
     logPrint("RPAREN",yytext,line_count);
	 ptr=new SymbolInfo(yytext,"RPAREN");
	 tokenPrint("RPAREN",yytext);
	 ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);  
	 yylval.symbol=ptr;
	 return RPAREN;
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 265 "2005053.l"
{ //tokenPrint("LCURL",yytext);
     //symtable->EnterScope();
	 logPrint("LCURL",yytext,line_count);
	 tokenPrint("LCURL",yytext);
	 ptr=new SymbolInfo(yytext,"LCURL");
	 ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);  
	 yylval.symbol=ptr;
	 return LCURL;
	 }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 275 "2005053.l"
{ //tokenPrint("RCURL",yytext);
     //symtable->ExitScope();
	 logPrint("RCURL",yytext,line_count);
	 tokenPrint("RCURL",yytext);
	 ptr=new SymbolInfo(yytext,"RCURL");
	 ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);  
	 yylval.symbol=ptr;
	 return RCURL;
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 285 "2005053.l"
{ //tokenPrint("LSQUARE",yytext);
    logPrint("LSQUARE",yytext,line_count);
	tokenPrint("LSQUARE",yytext);
	ptr=new SymbolInfo(yytext,"LSQUARE");
	ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);  
	yylval.symbol=ptr;
	return LTHIRD;
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 294 "2005053.l"
{ 
	//tokenPrint("RSQUARE",yytext);
     logPrint("RSQUARE",yytext,line_count); 
	 tokenPrint("RSQUARE",yytext);
	 ptr=new SymbolInfo(yytext,"RSQUARE");
	 ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);  
	 yylval.symbol=ptr;
	 return RTHIRD;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 304 "2005053.l"
{ 
	//tokenPrint("COMMA",yytext);
    logPrint("COMMA",yytext,line_count);
	tokenPrint("COMMA",yytext);
	ptr=new SymbolInfo(yytext,"COMMA");
	ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);  
	yylval.symbol=ptr;
	return COMMA;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 314 "2005053.l"
{ 
	//tokenPrint("SEMICOLON",yytext);
    logPrint("SEMICOLON",yytext,line_count);
	tokenPrint("SEMICOLON",yytext); 
	ptr=new SymbolInfo(yytext,"SEMICOLON");
	ptr->startlineSetter(line_count);
	 ptr->endlineSetter(line_count);  
	yylval.symbol=ptr;
	return SEMICOLON;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 324 "2005053.l"
{ //tokenPrint("ASSIGNOP",yytext);
       logPrint("ASSIGNOP",yytext,line_count);
	   tokenPrint("ASSIGNOP",yytext);
	   ptr=new SymbolInfo(yytext,"ASSIGNOP");
	   ptr->startlineSetter(line_count);
	   ptr->endlineSetter(line_count);  
	   yylval.symbol=ptr;
	   return ASSIGNOP;
 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 333 "2005053.l"
{ tokenPrint("NOT",yytext);
       logPrint("NOT",yytext,line_count);
	   ptr=new SymbolInfo(yytext,"NOT");
	   ptr->startlineSetter(line_count);
	   ptr->endlineSetter(line_count);  
	   yylval.symbol=ptr;
	   return NOT;
	 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 341 "2005053.l"
{ tokenPrint("ADDOP",yytext);
         logPrint("ADDOP",yytext,line_count);
		 ptr=new SymbolInfo(yytext,"ADDOP");
		 ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
		 yylval.symbol=ptr;
		 return ADDOP;
		 
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 350 "2005053.l"
{ tokenPrint("INCOP",yytext);
           logPrint("INCOP",yytext,line_count);
		   ptr=new SymbolInfo(yytext,"INCOP");
		   ptr->startlineSetter(line_count);
	       ptr->endlineSetter(line_count);  
	       yylval.symbol=ptr;
		   return INCOP;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 358 "2005053.l"
{   tokenPrint("DECOP",yytext);
	     logPrint("DECOP",yytext,line_count);
		 ptr=new SymbolInfo(yytext,"DECOP");
		 ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
	     yylval.symbol=ptr;
		 return DECOP;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 366 "2005053.l"
{ tokenPrint("LOGICOP",yytext);
           logPrint("LOGICOP",yytext,line_count);
		   ptr=new SymbolInfo(yytext,"LOGICOP");
		   ptr->startlineSetter(line_count);
	       ptr->endlineSetter(line_count);  
		   yylval.symbol=ptr;
		   return LOGICOP;
}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 375 "2005053.l"
{line_count++;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 376 "2005053.l"
{ tokenPrint("BITOP",yytext);;
         logPrint("BITOP",yytext,line_count);
		 ptr=new SymbolInfo(yytext,"BITOP");
		 ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
		 yylval.symbol=ptr;
		 return BITOP;
		 
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 385 "2005053.l"
{ tokenPrint("RELOP",yytext);
         logPrint("RELOP",yytext,line_count);
		 ptr=new SymbolInfo(yytext,"RELOP");
		 ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
		 yylval.symbol=ptr;
		 return RELOP;		 
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 393 "2005053.l"
{ tokenPrint("MULOP",yytext);
         logPrint("MULOP",yytext,line_count);
		 ptr=new SymbolInfo(yytext,"MULOP");
		  ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
		 yylval.symbol=ptr;
		 return MULOP;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 401 "2005053.l"
{ tokenPrint("CONST_INT",yytext);
          logPrint("CONST_INT",yytext,line_count);
		  ptr=new SymbolInfo(yytext,"CONST_INT");
		   ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
		  yylval.symbol=ptr;
		  return CONST_INT;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 409 "2005053.l"
{
	 tokenPrint("CONST_FLOAT",yytext);
     logPrint("CONST_FLOAT",yytext,line_count);
	 ptr=new SymbolInfo(yytext,"CONST_FLOAT");
	  ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
	 yylval.symbol=ptr;
	 return CONST_FLOAT;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 418 "2005053.l"
{
	fprintf(logout,"Error at line# %d: TOO_MANY_DECIMAL_POINTS %s\n",line_count,yytext);
	//errors++;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 422 "2005053.l"
{
	fprintf(logout,"Error at line# %d: ILLFORMED_NUMBER %s\n",line_count,yytext);
	//errors++;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 426 "2005053.l"
{
	fprintf(logout,"Error at line# %d: INVALID_ID_SUFFIX_NUM_PREFIX %s\n",line_count,yytext);
	//errors++;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 430 "2005053.l"
{
	char *temp=new char[strlen(yytext)-1];
	for(int i=1;i<strlen(yytext)-1;i++)
	{
			temp[i-1]=yytext[i];															
	}
	if(strlen(temp)>1)
	{   
		//cout<<strlen(temp)<<endl;
		tokenPrint("CONST_CHAR",charPrint(temp));
		logPrint("CONST_CHAR",charPrint(temp),line_count);
		ptr=new SymbolInfo(charPrint(temp),"CONST_CHAR");
		 ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
	    yylval.symbol=ptr;
	    return CONST_CHAR;
	}
	else{
		tokenPrint("CONST_CHAR",temp);
		logPrint("CONST_CHAR",temp,line_count);
		ptr=new SymbolInfo(temp,"CONST_CHAR");
		 ptr->startlineSetter(line_count);
	     ptr->endlineSetter(line_count);  
	    yylval.symbol=ptr;
	    return CONST_CHAR;
	}
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 457 "2005053.l"
{
	fprintf(logout,"Error at line# %d: MULTICHAR_CONST_CHAR %s\n",line_count,yytext);
	//errors++;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 462 "2005053.l"
{
	fprintf(logout,"Error at line# %d: EMPTY_CONST_CHAR %s\n",line_count,yytext);
	//errors++;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 466 "2005053.l"
{
	fprintf(logout,"Error at line# %d: UNFINISHED_CONST_CHAR %s\n",line_count,yytext);
	//errors++;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 470 "2005053.l"
{
    line_store=line_count;
	BEGIN(StringState);
	str = "";
	logStr="\"";
	flag=false;
}
	YY_BREAK

case YY_STATE_EOF(StringState):
#line 479 "2005053.l"
{
	string tokenName="UNFINISHED_STRING";
	fprintf(logout,"Error at line# %d: %s %s\n",line_count,tokenName.c_str(),logStr.c_str());
	//errors++;
	yyterminate();
	BEGIN(INITIAL);
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 486 "2005053.l"
{
	string tokenName="UNFINISHED_STRING";
	fprintf(logout,"Error at line# %d: %s %s\n",line_count,tokenName.c_str(),logStr.c_str());
	//errors++;
	line_count++;
	BEGIN(INITIAL);
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
#line 494 "2005053.l"
case 43:
/* rule 43 can match eol */
#line 495 "2005053.l"
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 495 "2005053.l"
{
   flag=true;
   line_count++;
   logStr +='\\';
   logStr +='\n';
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 502 "2005053.l"
{
	str +='\\';
	logStr += yytext;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 507 "2005053.l"
{
   str +='\t';
   logStr +=yytext;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 511 "2005053.l"
{
	str +='\n';
	logStr +=yytext;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 515 "2005053.l"
{
	str +='\v';
	logStr +=yytext;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 519 "2005053.l"
{
	str +='\b';
	logStr +=yytext;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 523 "2005053.l"
{
	str +='\a';
	logStr +=yytext;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 527 "2005053.l"
{
	str +='\f';
	logStr +=yytext;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 531 "2005053.l"
{
	str +='\r';
	logStr +=yytext;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 535 "2005053.l"
{
	str +='\0';
	logStr +=yytext;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 539 "2005053.l"
{
	str +='\'';
	logStr +=yytext;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 543 "2005053.l"
{
	str +='\"';
	logStr +=yytext;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 547 "2005053.l"
{
	str +='\\';
	logStr += yytext;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 553 "2005053.l"
{ str += yytext;logStr += yytext;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 554 "2005053.l"
{
	if(flag)
	{   
		logStr+="\"";
		//fprintf(tokenout,"<MULTI LINE STRING, %s>\n",str.c_str());	
		string tokenName="MULTI LINE STRING";
		fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_store,tokenName.c_str(),logStr.c_str()); 
	}
	else{
		logStr+="\"";
		//fprintf(tokenout,"<SINGLE LINE STRING, %s>\n",str.c_str());
		string tokenName="SINGLE LINE STRING";
		fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_store,tokenName.c_str(),logStr.c_str()); 
	
	}	
	BEGIN(INITIAL);
}
	YY_BREAK

case 59:
YY_RULE_SETUP
#line 574 "2005053.l"
{
	 BEGIN(multicomment);
	 line_store=line_count;
	 commentStr = "/*";	
}
	YY_BREAK

case YY_STATE_EOF(multicomment):
#line 580 "2005053.l"
{
	string tokenName="UNFINISHED_COMMENT";
	fprintf(logout,"Error at line# %d: %s %s\n",line_count,tokenName.c_str(),commentStr.c_str());
	//errors++;
	yyterminate();
	BEGIN(INITIAL);
 }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 588 "2005053.l"
{
	commentStr +='\n';
	line_count++;	
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 592 "2005053.l"
{
  commentStr += "*/";	
  string tokenName="MULTI LINE COMMENT";
  fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_store,tokenName.c_str(),commentStr.c_str()); 
  BEGIN(INITIAL);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 598 "2005053.l"
{commentStr +=yytext;}
	YY_BREAK

case 63:
YY_RULE_SETUP
#line 601 "2005053.l"
{
	 line_store=line_count;
	 BEGIN(singlecomment);
	 commentStr = "//";	
}
	YY_BREAK

case YY_STATE_EOF(singlecomment):
#line 607 "2005053.l"
{
	yyterminate();
	BEGIN(INITIAL);
 }
	YY_BREAK
case 64:
/* rule 64 can match eol */
#line 612 "2005053.l"
case 65:
/* rule 65 can match eol */
#line 613 "2005053.l"
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 613 "2005053.l"
{
   line_count++;
   commentStr +='\\';
   commentStr +='\n';
}
	YY_BREAK
case 67:
/* rule 67 can match eol */
#line 620 "2005053.l"
case 68:
/* rule 68 can match eol */
#line 621 "2005053.l"
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 621 "2005053.l"
{
	string tokenName="SINGLE LINE COMMENT";
    fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_store,tokenName.c_str(),commentStr.c_str()); 
	line_count++;	
	BEGIN(INITIAL);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 627 "2005053.l"
{commentStr +=yytext;}
	YY_BREAK

case 71:
YY_RULE_SETUP
#line 629 "2005053.l"
{ }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 630 "2005053.l"
{
	string tokenName="UNRECOGNIZED_CHAR";
	//errors++;
	fprintf(logout,"Error at line# %d: %s %s\n",line_count,tokenName.c_str(),yytext);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 635 "2005053.l"
{
	yyterminate();
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 639 "2005053.l"
ECHO;
	YY_BREAK
#line 1758 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 157 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 157 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 156);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 639 "2005053.l"

/* int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
    logout= fopen("log.txt","w");
	//tokenout= fopen("token.txt","w");
	yyin= fin;
	yylex();
	fclose(yyin);
	//fclose(tokenout);
	fclose(logout);
	return 0;
} */
